/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: false,
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Noto Sans"', 'sans-serif'],
        raj: ['Rajdhani', 'sans-serif'],
        poppins: ['Poppins', 'sans-serif'],
      },
      keyframes: {
        'heart-beat': {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.3)' },
        },
        'ping-slight': {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.2)' },
          '100%': { transform: 'scale(1)' },
        },
        pingOnce: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.4)' },
          '100%': { transform: 'scale(1)' }
        },
        fadeInOut: {
          '0%': { opacity: 0 },
          '30%': { opacity: 1 },
          '70%': { opacity: 1 },
          '100%': { opacity: 0 }
        }
      },
      animation: {
        'heart-beat': 'heart-beat 0.4s ease-in-out',
        'ping-slight': 'ping-slight 0.4s ease-in-out',
        pingOnce: 'pingOnce 0.3s ease-out',
        fadeInOut: 'fadeInOut 1.2s ease-in-out'
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
  safelist: [
    'grid-cols-2',
    'text-sm',
    'w-full',
    'block',
    'px-2',
    'py-1',
    'rounded',
    'border',
    'border-gray-300',
    'text-gray-700',
    'shadow-md',
    'rounded-xl',
    'px-4',
    'py-3',
    'bg-white',
    'bg-gradient-to-r',
    'from-pink-100',
    'to-red-100',
    'from-blue-100',
    'to-indigo-100',
    'from-yellow-100',
    'to-amber-100',
    'from-gray-100',
    'to-slate-100',
    'text-lg',
    'font-bold',
    'text-gray-800',
    'text-gray-600',
    'text-4xl',
    'mb-2',
    'space-y-2',
    'items-center',
    'text-center',
    'leading-relaxed',
    'hover:shadow-lg',
    'hover:scale-105',
    'active:scale-95',
    'transition-all',
    'duration-200',
        'pb-24',
        'h-[60px]',
        'fixed',
        'bottom-0',
        'z-50',
        'bg-black',
        'text-white',
        'py-2',
        'flex',
        'items-center',
        'justify-center',
        'rounded-full',
        'bg-blue-100',
        'hover:bg-blue-200',
        'text-blue-700',
        'hover:text-blue-800',
        'p-2',
        'transition-colors',
        'duration-200',
        'gap-2',
        'text-2xl',
        'font-bold',
        'text-gray-800',
        'dark:text-gray-100',
        'w-full',
        'max-w-md',
        'items-stretch',
        'flex-col',
        'md:flex-row',
        'px-4',
        'flex-1',
        'bg-red-500',
        'hover:bg-red-600',
        'text-white',
        'rounded-lg',
        'px-4',
        'py-2',
        'transition-colors',
        'duration-200',
        'hover:scale-105',
        // HomePage grid 需求
        'sm:px-8',
        'grid',
        'grid-cols-1',
        'sm:grid-cols-2',
        'md:grid-cols-4',
        'gap-4',
        'items-start',
        'max-w-sm',
        'max-w-xs',
        'mx-auto',
        'max-w-screen-lg',
        // Flex 卡片排列
        'justify-center',
        'gap-4',
        'w-48',
        'min-w-[10rem]',
        'text-center',
        'p-4',
        'rounded-xl',
        'shadow',
        'md:px-8'
  ]
}