import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import SEO from '@/components/SEO'

type Generation = { id: string; sourceImageUrl?: string | null; resultImageUrl?: string | null; productType?: string | null; outputRatio?: string | null; styleTitle?: string | null; pointsUsed: number; createdAt?: string | null }
function token() { return typeof window === 'undefined' ? '' : String(localStorage.getItem('auth_token') || localStorage.getItem('token') || '').trim() }
function fmt(value?: string | null) { if (!value) return '—'; const d = new Date(value); return Number.isNaN(d.getTime()) ? '—' : d.toLocaleString('zh-TW', { timeZone: 'Asia/Taipei', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }) }

export default function ProductImageHistoryPage() {
  const navigate = useNavigate(); const [rows, setRows] = useState<Generation[]>([]); const [loading,setLoading] = useState(true); const [error,setError] = useState('')
  useEffect(() => { const auth = token(); if (!auth) { navigate('/login?returnTo=%2Fmy-product-images'); return } ; void (async () => { try { const r = await fetch('/api/main?action=get-my-product-image-generations', { headers: { Authorization: `Bearer ${auth}` } }); const d = await r.json().catch(()=>({})); if (!r.ok) throw new Error(String(d?.error || '讀取商品圖紀錄失敗。')); setRows(Array.isArray(d?.generations)?d.generations:[]) } catch(e:any) { setError(e?.message || '讀取商品圖紀錄失敗。') } finally { setLoading(false) } })() }, [navigate])
  return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-6"><SEO title="我的商品圖紀錄｜RXV 夢想創作工作室" description="查看自己曾生成的商品圖。"/><div className="mx-auto max-w-6xl"><header className="rounded-3xl border border-emerald-200 bg-gradient-to-br from-emerald-50 via-white to-cyan-50 p-6 shadow-sm sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="inline-flex rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-800">登入帳號專用</span><h1 className="mt-3 text-3xl font-black text-slate-950">我的商品圖紀錄</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-700">這裡保留你用 AI 商品圖工具生成的原圖與結果圖，可重新查看或下載。</p></div><Link to="/tools/product-image-generator" className="inline-flex min-h-[46px] items-center justify-center rounded-xl bg-emerald-600 px-5 py-3 text-sm font-black !text-white hover:bg-emerald-700" style={{color:'#fff',WebkitTextFillColor:'#fff'}}>前往商品圖工具</Link></div></header>{error?<div className="mt-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 font-bold text-rose-800">{error}</div>:null}{loading?<div className="mt-6 rounded-3xl bg-white p-10 text-center text-slate-600 shadow-sm">正在讀取商品圖紀錄…</div>:rows.length===0?<section className="mt-6 rounded-3xl bg-white p-10 text-center shadow-sm"><h2 className="text-xl font-black text-slate-950">目前還沒有商品圖紀錄</h2><p className="mt-2 text-slate-600">完成一次商品圖生成後，原圖與結果圖會顯示在這裡。</p></section>:<section className="mt-6 grid gap-5 md:grid-cols-2">{rows.map(row=><article key={row.id} className="overflow-hidden rounded-3xl bg-white shadow-sm"><div className="grid grid-cols-2 gap-px bg-slate-100">{row.sourceImageUrl?<a href={row.sourceImageUrl} target="_blank" rel="noreferrer" className="bg-white p-2"><p className="mb-2 text-xs font-black text-slate-600">原始圖片</p><img src={row.sourceImageUrl} alt="原始商品圖" className="aspect-square w-full rounded-xl object-contain"/></a>:<div className="bg-white p-2 text-xs text-slate-400">未保存原始圖片</div>}{row.resultImageUrl?<a href={row.resultImageUrl} target="_blank" rel="noreferrer" className="bg-white p-2"><p className="mb-2 text-xs font-black text-emerald-700">生成結果</p><img src={row.resultImageUrl} alt="AI 生成商品圖" className="aspect-square w-full rounded-xl object-contain"/></a>:null}</div><div className="p-5"><h2 className="font-black text-slate-950">{row.styleTitle || 'AI 商品圖'}</h2><p className="mt-2 text-sm text-slate-600">{fmt(row.createdAt)}・扣除 {Number(row.pointsUsed||0).toLocaleString()} 點</p>{row.resultImageUrl?<a href={row.resultImageUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex rounded-xl bg-cyan-600 px-4 py-2.5 font-black !text-white hover:bg-cyan-700" style={{color:'#fff',WebkitTextFillColor:'#fff'}}>開啟／下載結果圖</a>:null}</div></article>)}</section>}</div></main>
}