import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const TaskCard = ({ task, onToggleStatus, onDelete, getCategoryColor, getCategoryName }) => {
    return (_jsxs("div", { className: "bg-white dark:bg-gray-800 rounded-xl mb-3 shadow-sm text-sm p-4", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsxs("div", { className: "flex items-center gap-3 flex-1 min-w-0", children: [_jsx("input", { type: "checkbox", checked: task.status === '已完成', onChange: () => onToggleStatus(task.id), className: "w-5 h-5 text-blue-600 bg-gray-100 dark:bg-gray-700 border-0 rounded focus:outline-none focus:ring-0 flex-shrink-0", style: { accentColor: '#3b82f6' } }), _jsx("div", { className: "flex-1 min-w-0", children: _jsx("div", { className: `font-bold text-lg truncate ${task.status === '已完成'
                                        ? 'line-through text-gray-500 dark:text-gray-400'
                                        : 'text-gray-900 dark:text-white'}`, children: task.title && task.title.trim() ? task.title : '（未命名任務）' }) })] }), _jsx("div", { className: `px-3 py-1 rounded-full text-sm font-medium flex-shrink-0 ${task.status === '已完成'
                            ? 'bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300'
                            : task.status === '進行中'
                                ? 'bg-yellow-100 dark:bg-yellow-900 text-yellow-700 dark:text-yellow-300'
                                : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300'}`, children: task.status })] }), (task.description?.trim() || task.title?.trim()) && (_jsx("div", { className: "text-sm text-gray-600 dark:text-gray-400 mt-1 mb-3 break-words", children: task.description?.trim() || task.title })), _jsxs("div", { className: "grid grid-cols-2 gap-3 mb-4 flex-wrap", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "w-3 h-3 rounded-full flex-shrink-0 border border-gray-300 dark:border-gray-600", style: { backgroundColor: getCategoryColor(task.category) } }), _jsx("span", { className: "text-sm text-gray-600 dark:text-gray-400 truncate", children: getCategoryName(task.category) })] }), _jsxs("div", { className: "text-sm text-gray-600 dark:text-gray-400", children: [_jsx("span", { className: "font-medium", children: "\u512A\u5148\u9806\u5E8F\uFF1A" }), _jsx("span", { className: `ml-1 ${task.priority === '高'
                                    ? 'text-red-600 dark:text-red-400'
                                    : task.priority === '中'
                                        ? 'text-yellow-600 dark:text-yellow-400'
                                        : 'text-green-600 dark:text-green-400'}`, children: task.priority })] }), _jsxs("div", { className: "text-sm text-gray-600 dark:text-gray-400", children: [_jsx("span", { className: "font-medium", children: "\u65E5\u671F\uFF1A" }), _jsx("span", { className: "ml-1", children: task.date || '未設定' })] }), _jsxs("div", { className: "text-sm text-gray-600 dark:text-gray-400", children: [_jsx("span", { className: "font-medium", children: "\u6642\u9593\uFF1A" }), _jsx("span", { className: "ml-1", children: task.startHour && task.startMinute
                                    ? `${task.startHour}:${task.startMinute.padStart(2, '0')} - ${task.endHour}:${task.endMinute.padStart(2, '0')}`
                                    : '未設定' })] })] }), (task.reminder && task.reminder !== '0') || task.remindBeforeMinutes ? (_jsxs("div", { className: "text-sm text-gray-600 dark:text-gray-400 mb-2", children: [_jsx("span", { className: "font-medium", children: "\u63D0\u9192\uFF1A" }), _jsxs("span", { className: "ml-1", children: ["\u4EFB\u52D9\u958B\u59CB\u524D ", task.remindBeforeMinutes || Number(task.reminder), " \u5206\u9418"] })] })) : null, onDelete && (_jsx("div", { className: "flex justify-end pt-3 border-t border-gray-100 dark:border-gray-700", children: _jsx("button", { onClick: () => onDelete(task.id, task.title), className: "bg-red-500 hover:bg-red-600 text-white text-sm flex items-center gap-1 px-3 py-2 rounded-lg shadow transition-all duration-200 hover:shadow-md transform hover:scale-[1.02] border-0", style: { background: '#ef4444', color: '#fff', border: 'none' }, children: "\uD83D\uDDD1\uFE0F \u522A\u9664" }) }))] }));
};
export default TaskCard;
