-- 短網址主表
create table if not exists public.short_links (
  id bigint generated by default as identity primary key,
  code text not null unique,
  original_url text not null,
  title text,
  description text,
  created_at timestamptz not null default now()
);

-- 點擊紀錄表
create table if not exists public.short_clicks (
  id bigint generated by default as identity primary key,
  code text not null,
  ip text,
  created_at timestamptz not null default now()
);

-- 若歷史版本 short_links 缺少欄位，補齊必要欄位
alter table if exists public.short_links
  add column if not exists code text,
  add column if not exists original_url text,
  add column if not exists created_at timestamptz default now();

create index if not exists idx_short_links_code on public.short_links (code);
create index if not exists idx_short_clicks_code on public.short_clicks (code);
create index if not exists idx_short_clicks_created_at on public.short_clicks (created_at desc);

